[2020-05-07 16:52:17 -0700] [9330] [ERROR] Invalid address: ('gorgonzola.cogsci.uci.edu', 20455)
[2020-05-07 16:52:17 -0700] [9330] [ERROR] Retrying in 1 second.
[2020-05-07 16:52:18 -0700] [9330] [ERROR] Invalid address: ('gorgonzola.cogsci.uci.edu', 20455)
[2020-05-07 16:52:18 -0700] [9330] [ERROR] Retrying in 1 second.
[2020-05-07 16:52:19 -0700] [9330] [ERROR] Invalid address: ('gorgonzola.cogsci.uci.edu', 20455)
[2020-05-07 16:52:19 -0700] [9330] [ERROR] Retrying in 1 second.
[2020-05-07 16:52:20 -0700] [9330] [ERROR] Invalid address: ('gorgonzola.cogsci.uci.edu', 20455)
[2020-05-07 16:52:20 -0700] [9330] [ERROR] Retrying in 1 second.
[2020-05-07 16:52:21 -0700] [9330] [ERROR] Invalid address: ('gorgonzola.cogsci.uci.edu', 20455)
[2020-05-07 16:52:21 -0700] [9330] [ERROR] Retrying in 1 second.
[2020-05-07 16:52:22 -0700] [9330] [ERROR] Can't connect to ('gorgonzola.cogsci.uci.edu', 20455)
2020-08-09 15:06:21,180 Scheduler started
2020-08-09 15:06:21,441 Scheduler started
2020-08-09 15:06:21,703 Scheduler started
2020-08-09 15:06:21,731 Looking for jobs to run
2020-08-09 15:06:21,743 No jobs; waiting until a job is added
2020-08-09 15:06:21,820 Looking for jobs to run
2020-08-09 15:06:21,829 No jobs; waiting until a job is added
2020-08-09 15:06:21,832 Scheduler started
2020-08-09 15:06:21,926 Scheduler started
2020-08-09 15:06:21,966 Scheduler started
2020-08-09 15:06:22,044 Looking for jobs to run
2020-08-09 15:06:22,058 No jobs; waiting until a job is added
2020-08-09 15:06:22,111 Scheduler started
2020-08-09 15:06:22,118 Scheduler started
2020-08-09 15:06:22,126 Scheduler started
2020-08-09 15:06:22,156 Looking for jobs to run
2020-08-09 15:06:22,195 No jobs; waiting until a job is added
2020-08-09 15:06:22,222 Looking for jobs to run
2020-08-09 15:06:22,232 No jobs; waiting until a job is added
2020-08-09 15:06:22,343 Looking for jobs to run
2020-08-09 15:06:22,359 No jobs; waiting until a job is added
2020-08-09 15:06:22,459 Looking for jobs to run
2020-08-09 15:06:22,463 Looking for jobs to run
2020-08-09 15:06:22,486 No jobs; waiting until a job is added
2020-08-09 15:06:22,549 No jobs; waiting until a job is added
2020-08-09 15:06:22,578 Looking for jobs to run
2020-08-09 15:06:22,588 No jobs; waiting until a job is added
[2025-04-27 17:04:00 -0700] [29747] [CRITICAL] WORKER TIMEOUT (pid:29750)
[2025-04-28 09:31:55 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30591)
2025-04-28 09:32:29,859 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
2025-04-28 09:33:28,479 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
[2025-04-28 09:33:29 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30592)
[2025-04-28 09:33:29 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30596)
2025-04-28 09:33:58,087 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
2025-04-28 09:34:19,938 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
[2025-04-28 09:34:28 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30622)
[2025-04-28 09:34:28 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30623)
[2025-04-28 09:35:28 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30625)
[2025-04-28 09:35:28 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30626)
[2025-04-28 09:36:29 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30595)
[2025-04-28 09:36:29 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30619)
[2025-04-28 09:37:33 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30593)
[2025-04-28 09:37:33 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30629)
[2025-04-28 09:37:33 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30630)
[2025-04-28 09:42:10 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30631)
[2025-04-28 09:42:10 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30638)
[2025-04-28 09:43:10 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30590)
[2025-04-28 09:43:10 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30637)
[2025-04-28 09:43:17 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30643)
[2025-04-28 09:44:02 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30598)
[2025-04-28 09:44:02 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30647)
[2025-04-28 09:46:17 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30628)
[2025-04-28 09:46:17 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30648)
[2025-04-28 09:50:06 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30654)
[2025-04-28 09:58:45 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30655)
[2025-04-28 10:03:51 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30649)
[2025-04-28 10:08:29 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30651)
[2025-04-28 10:18:30 -0700] [30587] [CRITICAL] WORKER TIMEOUT (pid:30594)
2025-04-28 10:24:07,212 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
2025-04-28 10:24:42,462 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
[2025-04-28 16:32:38 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31473)
[2025-04-28 16:32:39 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31478)
[2025-04-28 16:34:52 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31500)
[2025-04-28 16:36:29 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31471)
[2025-04-28 16:37:37 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31476)
[2025-04-28 16:40:54 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31506)
[2025-04-28 16:41:57 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31503)
[2025-04-28 16:42:08 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31512)
[2025-04-28 16:42:17 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31474)
[2025-04-28 16:42:18 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31507)
[2025-04-28 16:43:08 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31472)
[2025-04-28 16:43:28 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31517)
[2025-04-28 16:44:24 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31475)
[2025-04-28 16:44:27 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31477)
[2025-04-28 16:44:28 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31521)
[2025-04-28 16:44:31 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31499)
[2025-04-28 16:48:01 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31520)
[2025-04-28 17:16:44 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31519)
[2025-04-28 17:35:12 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31524)
[2025-04-28 17:35:12 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31526)
[2025-04-28 17:35:51 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31527)
[2025-04-28 17:35:53 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31582)
[2025-04-28 19:00:45 -0700] [31468] [CRITICAL] WORKER TIMEOUT (pid:31532)
[2025-04-29 15:08:39 -0700] [33032] [CRITICAL] WORKER TIMEOUT (pid:33038)
[2025-05-08 12:03:43 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45848)
[2025-05-08 12:09:49 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45854)
[2025-05-08 12:12:34 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45849)
[2025-05-08 12:12:34 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45850)
[2025-05-08 12:12:34 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45851)
[2025-05-08 12:12:34 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45852)
[2025-05-08 12:12:34 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45853)
[2025-05-08 12:12:34 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45909)
[2025-05-08 12:14:41 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45918)
[2025-05-08 12:14:41 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45923)
[2025-05-08 12:14:42 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45846)
[2025-05-08 12:59:34 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45914)
[2025-05-08 13:02:56 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45976)
[2025-05-08 13:07:24 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45920)
[2025-05-08 13:07:45 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45847)
[2025-05-08 13:08:07 -0700] [45843] [CRITICAL] WORKER TIMEOUT (pid:45919)
[2025-05-11 15:02:01 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49503)
2025-05-11 15:02:07,942 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
2025-05-11 15:02:18,761 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
[2025-05-11 15:02:30 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49499)
2025-05-11 15:02:37,133 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
2025-05-11 15:02:48,611 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
[2025-05-11 15:05:02 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49502)
[2025-05-11 15:06:41 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49498)
[2025-05-11 15:06:43 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49501)
[2025-05-11 15:07:44 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49537)
[2025-05-11 15:09:34 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49533)
[2025-05-11 15:11:47 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49504)
[2025-05-11 15:11:47 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49529)
[2025-05-11 15:13:43 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49496)
[2025-05-11 16:22:09 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49500)
[2025-05-11 16:24:41 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49538)
[2025-05-11 16:24:41 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49551)
[2025-05-11 16:25:41 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49543)
[2025-05-11 16:25:41 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49626)
[2025-05-11 16:26:41 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49547)
[2025-05-11 16:26:41 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49632)
[2025-05-11 16:27:41 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49497)
[2025-05-11 16:27:41 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49636)
[2025-05-11 16:31:50 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49535)
[2025-05-11 16:31:50 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49631)
[2025-05-11 16:33:01 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49527)
[2025-05-11 16:33:01 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49630)
[2025-05-11 16:33:26 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49546)
[2025-05-11 17:09:49 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49645)
2025-05-11 17:14:17,411 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
2025-05-11 17:14:20,066 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
2025-05-11 17:14:24,667 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
2025-05-11 17:14:29,964 Exception on /.well-known/gpc.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/psiturk/Library/Python/3.7/lib/python/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .well-known/gpc.json
[2025-05-11 17:19:29 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49646)
[2025-05-11 17:20:25 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49638)
[2025-05-11 17:23:10 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49696)
[2025-05-11 17:25:56 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49651)
[2025-05-11 17:30:27 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49700)
[2025-05-11 18:01:34 -0700] [49493] [CRITICAL] WORKER TIMEOUT (pid:49637)
